let piyushSirTranscript = `All right, so hey everyone, welcome back, welcome to another exciting video! Is video ke andar mere paas aapke liye ek bahut hi exciting opportunity hai — real world open source projects mein contribute karne ka mauka! Aaj hum baat karne wale hain ek aise organization ke baare mein jo aapko enable karta hai ki aap real-world impactful open-source projects par kaam karein, aur uske return mein aapko milti hai exposure, career opportunities aur even cash rewards bhi! Is organization ka naam hai Code for GovTech (C4GT). Hum jaanenge ki C4GT kya hai, iska kya motive hai, aur aap iske Dedicated Mentoring Program (DMP) 2025 mein kaise participate kar sakte ho.

C4GT ka main motive yeh hai ki yeh log developers ko encourage karte hain real-world open source projects mein contribute karne ke liye. Agar aap inki website par jaoge, aapko kai sari partner organizations milengi jinke saath aap kaam kar sakte ho. DMP 2025, yaani Dedicated Mentoring Program, pehle bhi 3 baar ho chuka hai — 2022 se shuru hua tha — aur is baar bhi aapko milta hai ek structured mentorship, ek proper stipend of ₹1 lakh for 3 months, aur real-world experience. Jo bhi relevant links hain registration ke liye, wo description mein mil jayenge.

Ab baat karte hain kaise apply karna hai. Sabse pehle aapko C4GT ki website par register karna hoga, phir ek additional form bharna hoga jisme aapka background, aapke interests, aur kaunsa tech stack aap choose karna chahte ho — jaise coding, UI/UX, ya AI applications — yeh sab include hoga. Uske baad aapko ek project select karna hai jo inki website par listed hai. Projects kaafi diverse hain — Kotlin, React, Angular, TypeScript, JavaScript, Python, Docker, DevOps, LLMs jaise GPT — toh aap apne interest ke hisaab se choose kar sakte ho. Har project ke saath aapko ek GitHub issue diya jaayega jisse aapko pata chalega kya karna hai aur kya avoid karna hai.

Jab aap project choose kar loge, tab aapko ek proposal submit karna hoga — jaise GSoC mein hota hai — ek template ke through. Agar aapka proposal select hota hai, toh aapko ek interview ke liye bulaaya ja sakta hai jahan aapka motivation aur understanding test ki jaayegi. Uske baad ek masterclass bhi hogi jo aapko guide karegi kaise aage proceed karna hai. Eligibility kaafi broad hai — agar aap college student ho, working professional ho, ya tech enthusiast ho jisko tech mein interest hai, aap apply kar sakte ho. Lekin aapke paas relevant skills zaroor honi chahiye kyunki bina skill ke contribute karna mushkil hoga.

Yeh ek remote opportunity hai, lekin ho sakta hai kabhi-kabhi travel bhi karna pade, so be prepared. Participants ko mid-May se mid-September tak available rehna hoga. Working professionals apna schedule zaroor check karein kyunki minimum commitment 20 hours per week ka hai. College students ke liye yeh ek golden chance hai kyunki aapko milta hai ek actual project par kaam karne ka experience, one-on-one mentorship, aur career growth opportunities bhi. Aap samjhoge ki real-world codebase kaise dikhta hai, pull requests kaise banate hain, aur bugs kaise solve karte hain — yeh sab kaafi valuable experiences honge.

Toh reward kya hai? Sabse pehle learning — jo priceless hai. Fir ₹1 lakh ka stipend, one-on-one mentorship, aur career ke naye raaste. Toh guys, agar aap tech mein serious ho, coding seekh rahe ho, aur real-world exposure chahte ho, toh C4GT ek badiya opportunity hai. Saare relevant links niche description mein mil jayenge. Apply zaroor karna, achhe se proposal likhna, aur GitHub issue ko properly samajhna. All the best to everyone participating and hats off to the C4GT team for bringing this initiative. Milte hain next video mein, tab tak ke liye bye-bye and take care!`;

export {piyushSirTranscript}